language: node_js

node_js:
  - node

branches:
  only:
  - main

script:
  - echo "BUILDING AND PUSHING A NEW IMAGE OF THE CODE"

deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  region: us-east-2
  app: Elly Tale
  env: EllyTale-env
  bucket_name: elasticbeanstalk-us-east-2-126803918895
  on:
    repo: vrapeutic/Ellie-Tale
    branch: main
  skip_cleanup: 'true'
