language: node_js

node_js:
  - node

branches:
  only:
  - main

script:
  - echo "BUILDING AND PUSHING A NEW IMAGE OF THE CODE"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build --tag $DOCKER_USERNAME/illy-tale-webxr:latest .
  - docker images
  - docker image push $DOCKER_USERNAME/illy-tale-webxr

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJOWVC6JGYI4KPFQQ
  secret_access_key:
    secure: Xzs3+fGtxoFdkWgaDZxC0Fxn5phZVnAgGpYN6D+YhKdg3rGqNet6hDKAoe8EAfkpwy0Cxd5o/ohZVKHr65Cs9YACKw/LHRyvXSV++W91p4VN2Zxn67R950/3ulsjd/4fWpsYZ/2v8wpq4seGoa6xrLXgamFC0aDqOxfos2Q9/8XDaKfzdPc9Fx8BgnkjamS/uz6WFs2n2kD0cnmFjwEW7h5jjyLkCdnBJ5gELWA5GCrsJwJVfHUNO87GD5ZkV7TbtiI0mJyd10aNivo1/qW690uz/TYH35uW/LfoXRJgGPlje9AOoRiFkhaNGvZufMW8OQAo+VJqQMdMAtUbYtM+0dgUu1ix0uqu8igbW6oDMJmKZAFezkK78BgdR8Wu34CrVYg4ipzln9nYlfyMYGEpWMtCFnqHCfWHUMCpXbDr++g6knVo4NUkNsyQ1Cjj2ewcNhnJ5AiGFLat7Yo1pBbO3QJDP+udmCES5Xr5ipI+BgZRKl5x+8NP3Q3kIqsxnXvdOrxZhIoVetcE2M5kFBTXaDnAl52e1lJeVFv9yjL2wI1gbg1ekBYGDLR/5GApjlcHp3FwNLC/JGRJ//UiQVjABSGOATw2n65IxAUc3o47kqCZdnzS2xnHhUKwYXAwyV0l6gX1cfMpYl280b8ssyBl5I/7/bKFb1Y/cD7HDxnZGoo=
  region: us-east-2
  app: Elly Tale
  env: EllyTale-env
  bucket_name: elasticbeanstalk-us-east-2-126803918895
  on:
    repo: vrapeutic/Ellie-Tale
    branch: main
  skip_cleanup: 'true'
