
language: node_js

node_js:
  - node

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build --tag $DOCKER_USERNAME/elly-tale-webxr:latest .
  - docker images
  - docker image push $DOCKER_USERNAME/elly-tale-webxr

script:
  - echo "TEST DONE"